version: "3.9"

services:

  localstack:
    image: localstack/localstack:3.4.0@sha256:54fcf172f6ff70909e1e26652c3bb4587282890aff0d02c20aa7695469476ac0
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sns, sqs, kms
      LOCALSTACK_HOST: localstack
    volumes:
      - ./config/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4566" ]
    ports:
      - "4566:4566"

  mongo:
    image: mongo:5.0@sha256:54bcd8da3ea5eec561b68c605046c55c6b304387dc4c2bf5b3a5f5064fbb7495
    expose:
      - 27017
    ports:
      - "27017:27017"
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 10

  wm-application-manager:
    image: ${MOCK_IMAGE}
    ports:
      - "9970:8080"

  wm-account-manager:
    image: ${MOCK_IMAGE}
    ports:
      - "9930:8080"

  wm-dwp-guid:
    image: ${MOCK_IMAGE}
    ports:
      - "9980:8080"

  ms-identity-status:
    image: ${APP_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - ACCOUNT_MANAGER_BASE_URL=http://wm-account-manager:8080
      - APPLICATION_ACCOUNT_REGISTRATIONS_LIMIT=10
      - APPLICATION_MANAGER_BASE_URL=http://wm-application-manager:8080
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_ENCRYPTION_KMS_KEY_CACHE=true
      - AWS_ENCRYPTION_KMS_OVERRIDE=http://localstack:4566
      - AWS_ENCRYPTION_MESSAGE_DATA_KEY_ID=alias/test_event_request_id
      - AWS_ENCRYPTION_REGION=eu-west-2
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - COORDINATOR_BASE_URL=http://wm-application-manager:8080
      - FEATURE_DATA_CHANGESTREAM_ENABLED=false
      - FEATURE_ENCRYPTION_MESSAGING_ENABLED=false
      - MS_IDENTITY_STATUS_CONNECTION_TIMEOUT=30000
      - SCHEDULE_RESET_REGISTRATIONS_COUNT=0-59/10 * * * * *
      - SPRING_DATA_MONGODB_DATABASE=identity
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - UK_GOV_DWP_AUTH_TOKEN_SERVICE_URL=/citizen-information/oauth2/token
      - UK_GOV_DWP_GUID_SERVICE_GUID_CREDENTIALS={"client_id":"sampleClientId", "secret":"sampleSecret"}
      - UK_GOV_DWP_GUID_SERVICE_GUID_URL=/dwp-guid-service/v1/dwp-guid
      - UK_GOV_DWP_GUID_SERVICE_NINO_URL=/dwp-guid-service/v1/nino
      - UK_GOV_DWP_HEALTH_CHANGESTREAM_CHANNELS[0]_COLLECTION=identity
      - UK_GOV_DWP_HEALTH_CHANGESTREAM_CHANNELS[0]_DATABASE=identity
      - UK_GOV_DWP_HEALTH_CHANGESTREAM_CHANNELS[0]_ROUTING_KEY=identity.changed
      - UK_GOV_DWP_HEALTH_CHANGESTREAM_CHANNELS[0]_SKIP_DECRYPTION=true
      - UK_GOV_DWP_HEALTH_COORDINATOR_OUTBOUND_QUEUE_NAME_IDENTITY_RESPONSE=update_coordinator_idv_queue
      - UK_GOV_DWP_HEALTH_COORDINATOR_OUTBOUND_ROUTING_KEY_IDENTITY_RESPONSE=pip_identity_coordinator_outbound_routing
      - UK_GOV_DWP_HEALTH_COORDINATOR_OUTBOUND_TOPIC=update_coordinator_idv_topic
      - UK_GOV_DWP_HEALTH_GUIDEVENT_OUTBOUND_ROUTINGKEY=pip_identity_outbound_routing
      - UK_GOV_DWP_HEALTH_GUIDEVENT_OUTBOUND_TOPIC=pip_identity_event_guid
      - UK_GOV_DWP_HEALTH_IDENTITY_REQUEST_OUTBOUND_ROUTING_KEY=pip_identity_inbound_routing
      - UK_GOV_DWP_HEALTH_IDENTITY_REQUEST_OUTBOUND_TOPIC_NAME=pip_identity_event_nino
      - UK_GOV_DWP_HEALTH_IDENTITY_RESPONSE_INBOUND_QUEUE_NAME=pip_idv_outcome
      - UK_GOV_DWP_HEALTH_IDENTITY_RESPONSE_INBOUND_ROUTING_KEY=pip_identity_inbound_routing
      - UK_GOV_DWP_HEALTH_INTEGRATION_MESSAGING_TYPE=aws
      - UK_GOV_DWP_HEALTH_INTEGRATION_OUTBOUND_TOPIC_EXCHANGE=pip_identity_event_nino
      - UK_GOV_DWP_HEALTH_INTEGRATION_OUTBOUND_TOPIC_EXCHANGE=stream-topic
      - UK_GOV_DWP_HEALTH_INTEGRATION_SNS_ENDPOINT_OVERRIDE=http://localstack:4566
      - UK_GOV_DWP_HEALTH_INTEGRATION_SQS_ENDPOINT_OVERRIDE=http://localstack:4566
      - UK_GOV_DWP_HEALTH_PIPCS_OUTBOUND_ROUTING_KEY=pip_identity_outbound_routing
      - UK_GOV_DWP_HEALTH_PIPCS_OUTBOUND_TOPIC=update_pipcs_idv_topic
      - UK_GOV_DWP_INTEGRATION_GATEWAY_BASE_URL=http://wm-dwp-guid:8080
    depends_on:
      localstack:
        condition: service_healthy
      mongo:
        condition: service_healthy
      wm-application-manager:
        condition: service_started
      wm-account-manager:
        condition: service_started
      wm-dwp-guid:
        condition: service_started
    expose:
      - 8080
    ports:
      - "8080:8080"
      - "5009:5009"
    entrypoint:
      - java
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
      - -jar
      - /ms-identity-status.jar

  api-tests:
    profiles: [ api-test ]
    container_name: api-test
    image: '${MAVEN_IMAGE}'
    entrypoint: /bin/bash -c
    command:
      - |
        until [ `curl -s -o /dev/null -w "%{http_code}" http://ms-identity-status:8080/actuator/health` = "200" ]; do echo "service not available, sleeping 10."; sleep 10; done
        sleep 30
        mvn ${MVN_OPTS} verify -Papi-component-tests
    working_dir: /usr/src
    depends_on:
      - ms-identity-status
    environment:
      AWS_ACCESS_KEY: aws-access-key
      AWS_SECRET_KEY: aws-secret-key
      AWS_ENDPOINT_OVERRIDE: http://localstack:4566
      HOST: http://ms-identity-status
      PORT: 8080
      MONGODB_HOST: mongo
      MONGO_PORT: 2701
      AWS_REGION: eu-west-2
      REQUEST_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:pip_identity_event_nino
      REQUEST_ROUTING_KEY: pip_identity_inbound_routing
      RESPONSE_ROUTING_KEY: pip_identity_outbound_routing
      REQUEST_QUEUE_URL: http://localstack:4566/000000000000/pip_idv_outcome
      DEAD_LETTER_QUEUE_URL: http://localstack:4566/000000000000/pip_idv_outcome_dlq
      RESPONSE_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:update_pipcs_idv_topic
      RESPONSE_PIPCS_QUEUE_URL: http://localstack:4566/000000000000/update_pipcs_idv_queue
      RESPONSE_PIPSERVICE_QUEUE_URL: http://localstack:4566/000000000000/update_coordinator_idv_queue
    volumes:
      - .:/usr/src
      - ${MVN_M2}:/root/.m2
      - ${MVN_SETTINGS_FILE}:/root/.m2/settings.xml
      - ./target/test/reports:/usr/src/target/test-reports
