version: "2.1"

services:

  localstack:
    image: localstack/localstack-full:1.0.1@sha256:6753b5e666247d984f6e57dbe1781e757f175a0c905da0dc9a62b49c443f4ecf
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=eu-west-2
      - SERVICES=sns,sqs,kms
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4566/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "4566:4566"
    volumes:
      - ./config/localstack:/docker-entrypoint-initaws.d

  mongodb-repl:
    image: mongo:5.0@sha256:ee514514754ffdb13597a894bdae90fdabbe4c0926bf96b40a84d1233782bcc1
    volumes:
      - ./config/mongo-replicator/submission.js:/tmp/submission.js
      - ./config/mongo-replicator/replicate.js:/tmp/replicate.js
      - ./config/mongo-replicator/setup.sh:/tmp/setup.sh
    command: /bin/sh /tmp/setup.sh
    depends_on:
      mongo-primary:
        condition: service_healthy
      mongo-secondary:
        condition: service_healthy

  mongo-primary:
    image: mongo:5.0@sha256:ee514514754ffdb13597a894bdae90fdabbe4c0926bf96b40a84d1233782bcc1
    command: --replSet rs0 --bind_ip_all
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "27017:27017"

  mongo-secondary:
    image: mongo:5.0@sha256:ee514514754ffdb13597a894bdae90fdabbe4c0926bf96b40a84d1233782bcc1
    command: --replSet rs0 --bind_ip_all
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "27018:27017"
    depends_on:
      mongo-primary:
        condition: service_started
