app_name: @project.artifactId@
app_version: @project.version@

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: identity

uk:
  gov:
    dwp:
      health:
        integration:
          outbound-topic-exchange: stream-topic
          sns-endpoint-override: http://localhost:4566
          sqs-endpoint-override: http://localhost:4566
          aws-region: EU_WEST_2
          outbound-queue: update_pipcs_idv_queue
        inbound:
          topic: pip_identity_event_nino
          queueNameIdentityResponse: pip_idv_outcome
          routingKeyIdentityResponse: pip_identity_inbound_routing
        outbound:
          topic: update_pipcs_idv_topic
          queueNameIdentityResponse: update_pipcs_idv_queue
          routingKeyIdentityResponse: pip_identity_outbound_routing
          guidEvent:
            topic: pip_identity_event_guid
            routingKey: pip_identity_outbound_routing

sns:
  msg:
    pip_identity_routing_key: new.event

sqs:
  msg:
    queue-name: pip_idv_outcome
    pip_identity_routing_key-prefix: new

feature:
  mongo:
    versioned:
      api:
        enabled: true
  encryption:
    messaging:
      enabled: false

application:
  manager:
    base:
      url: http://localhost:9970

account:
  manager:
    base:
      url: http://localhost:9930

max:
  timeout:
    millis: 29000

aws:
  encryption:
    message-data-key-id: alias/test_event_request_id
    region: eu-west-2
    kms-key-cache: true
    kms-override: http://localhost:4566
