app_name: @project.artifactId@
app_version: @project.version@

logging:
  level:
    root: INFO

spring:
  main:
    banner-mode: 'off'

server:
  port: 8080

feature:
  mongo:
    versioned:
      api:
        enabled: true
  encryption:
    messaging:
      enabled: false
  data:
    changestream:
      enabled: false

application:
  manager:
    base:
      url: /
max:
  timeout:
    millis: 29000

uk:
  gov:
    dwp:
      health:
        changestream:
          channels:
            - collection: identity
              routingKey: identity.changed
              database: identity
management:
  endpoint:
    health:
      show-details: always
